version: '3'
 
services:
  notes_gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 9229:9229
    volumes: 
      - .:/app
      - /app/node_modules
    command: npm run start.watch
