version: '3'
 
services:
  notes_db:
    image: harperdb/hdb:latest
    environment: 
      - INIT_HDB_USERNAME=HDB_ADMIN
      - INIT_HDB_PASSWORD=password
    ports:
      - 9925:9925
      - 31283:31283
    volumes:
      - notes_db_data:/opt/harperdb/hdb/
  notes_gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile.dev
    volumes: 
      - ./gateway:/app
      - /app/node_modules
    command: npm run start.watch
  cors_proxy:
    build:
      context: ./cors-proxy
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment: 
      - GATEWAY=notes_gateway
      - GATEWAY_PORT=8080
    volumes: 
      - ./cors-proxy:/app
      - /app/node_modules
    command: npm run start

volumes:
  notes_db_data:
