/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface FskNote {
        /**
          * HTML property note-id: id of the note to display
         */
        "noteId": number;
    }
    interface FskNotesList {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLFskNoteElement extends Components.FskNote, HTMLStencilElement {
    }
    var HTMLFskNoteElement: {
        prototype: HTMLFskNoteElement;
        new (): HTMLFskNoteElement;
    };
    interface HTMLFskNotesListElement extends Components.FskNotesList, HTMLStencilElement {
    }
    var HTMLFskNotesListElement: {
        prototype: HTMLFskNotesListElement;
        new (): HTMLFskNotesListElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "fsk-note": HTMLFskNoteElement;
        "fsk-notes-list": HTMLFskNotesListElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface FskNote {
        /**
          * HTML property note-id: id of the note to display
         */
        "noteId"?: number;
        "onCloseNote"?: (event: CustomEvent<any>) => void;
    }
    interface FskNotesList {
        /**
          * Sent when user selects a note by clicking on it
          * @event
         */
        "onSelectedNote"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-root": AppRoot;
        "fsk-note": FskNote;
        "fsk-notes-list": FskNotesList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "fsk-note": LocalJSX.FskNote & JSXBase.HTMLAttributes<HTMLFskNoteElement>;
            "fsk-notes-list": LocalJSX.FskNotesList & JSXBase.HTMLAttributes<HTMLFskNotesListElement>;
        }
    }
}
